name: DataMiner CICD Automation

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches:
      - main
      - master
    tags:
      - "[0-9]+.[0-9]+.[0-9]+.[0-9]+"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  CI:
    uses: SkylineCommunications/_ReusableWorkflows/.github/workflows/Automation Master Workflow.yml@main
    with:
      referenceName: ${{ github.ref_name }}
      runNumber: ${{ github.run_number }}
      referenceType: ${{ github.ref_type }}
      repository: ${{ github.repository }}
      owner: ${{ github.repository_owner }}
      sonarCloudProjectName: skylinecommunications_synergylca
      # The API-key: generated in the DCP Admin app (https://admin.dataminer.services/) as authentication for a certain DataMiner System.
    secrets:
      api-key: ${{secrets.DATAMINER_DEPLOY_KEY}}
      sonarCloudToken: ${{ secrets.SONAR_TOKEN }}
  
  CD:   
    name: CD
    environment: staging
    runs-on: ubuntu-latest
    needs: CI
    steps:
       - uses: actions/checkout@v4

       - name: Find .sln file
         id: findSlnFile 
         run: |
           echo solutionFilePath=$(find . -type f -name '*.sln') >> $GITHUB_OUTPUT
         shell: bash

       - name: Skyline DataMiner Deploy Action Development
         uses: SkylineCommunications/Skyline-DataMiner-Deploy-Action@v1
         with:
           # Stage deploy
           stage: All
           # The API-key: generated in the DCP Admin app (https://admin.dataminer.services/) as authentication for a certain DataMiner System.
           api-key: ${{ secrets.DATAMINER_DEPLOY_KEY }}
           solution-path: ${{ steps.findSlnFile.outputs.solutionFilePath }}
           artifact-name: ${{ github.repository }} ${{ github.ref_name }}_B${{ github.run_number }}
           build-number: ${{ github.run_number }}
